#!/usr/bin/env sh

_() {
  YEAR="2022"
  echo "Github Username: "
  read -r USERNAME

  [ -z "$USERNAME" ] && exit 1
  [ ! -d $YEAR ] && mkdir $YEAR

  cd "${YEAR}" || exit
  git init
  echo "Since I was born in **${YEAR}** I've been writing code - Generated by https://github.com/HongxuanG/TravelBack" \
    >README.md
  git add .
  GIT_AUTHOR_DATE="${YEAR}-08-26T18:00:00" \
    GIT_COMMITTER_DATE="${YEAR}-08-26T18:00:00" \
    git commit -m "${YEAR}"
  git remote add origin "git@github.com:${USERNAME}/${YEAR}.git"
  git branch -M main
  git push -u origin main -f
  cd ..
  rm -rf "${YEAR}"

  echo
  echo "Cool, check your profile now: https://github.com/${USERNAME}"
} && _

unset -f _
